version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: waste
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo-data: